name: Automerge Feature
on:
  push:
    branches: 
    - "feature/*"
jobs:
  check-commit:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^MERGE:*'
          error: 'The last push of this feature is not ready to be merged with the develop branch'
  automerge:
    name: Automerge
    needs:
      - check-commit
      - pruebas-flask
      - pruebas-angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge feature to develop branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: dev
          github_token: ${{ github.token }}