name: Pruebas Flask
on:
  push:
    branches: 
    - "feature/*"
jobs:
  pruebas-flask:
    name: Pruebas Flask
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Instalación de librerías y dependencias de python
      run: |
        python -m pip install --upgrade pip
        pip install -r flaskr/requirements.txt
    - name: Correr pruebas de flask
      id: correr-pruebas
      run: python -m unittest discover -s flaskr/tests
    - name: Cálculo de cubrimiento (python)
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s flaskr/tests
          coverage report -m