name: Pruebas Flask
on:
  push:
    branches: 
    - "feature/*"
jobs:
  pruebas-angular:
    name: Pruebas Angular
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuracion de entorno de angular
      uses: actions/setup-node@v2
      with:
        node-version: '14.15'
    - name: Instalacion de librerías y dependencias de angular
      run: |
        cd ./front-end/tutorial-canciones/
        npm i
        npm install -g @angular/cli
    - name: Instalacion de Google Chrome para pruebas de angular
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - name: Corre pruebas de angular
      run: |
        cd front-end/tutorial-canciones/ && CHROMIUM_BIN=$(which chrome) ng test --watch=false --browsers=ChromeHeadless